import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

// ✅ Clerk Provider Import
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get me a chai - A website for chai lovers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} min-h-screen w-full bg-black text-white flex flex-col`}
        >
          {/* ✅ Navbar */}
          <NavBar />

          {/* ✅ Background Wrapper + Content */}
          <main
            className="relative w-full flex-1 pt-20
            bg-[#000000] 
            bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] 
            bg-[size:20px_20px]"
          >
            {children}
          </main>

          {/* ✅ Footer */}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}